# Generated by Django 4.2.6 on 2023-11-13 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cuerpo', models.CharField(max_length=255)),
            ],
        ),
    ]
