# Generated by Django 4.2.6 on 2023-11-14 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 11, 14)),
        ),
    ]
