# Generated by Django 4.2.6 on 2023-11-15 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('deportes', 'DEPORTES'), ('politica', 'POLITICA'), ('economia', 'ECONOMIA'), ('tecnologia', 'TECNOLOGIA')], max_length=40),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 11, 15)),
        ),
    ]
